version: "2"
engines:
  checks:
    similar-code:
      config:
        threshold: 39
    identical-code:
      config:
        threshold: 39
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  method-complexity:
    config:
      threshold: 8
