version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 39
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  method-complexity:
    config:
      threshold: 8
