version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 3
  file-lines:
    config:
      threshold: 254
  method-complexity:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 3
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 40
