language: python
cache: pip
python:
  # note, travis only has 3.6 as the latest. We should check back later to upgrade to 3.7
  - "3.6"
install:
  - pip install -r requirements-dev.txt
  - pip install codecov python-Levenshtein
# commands to run, must exit 0 to pass
script:
  - flake8
  - yapf --parallel --verbose --recursive --style .style.yapf --exclude 'py37-mac' --diff .
  - find . -type f -name "*.py" ! -path "./py37-mac/*" ! -path "./merging_tests/*" | xargs pylint
  - vulture --exclude "*py37-mac*" .
  - xenon --max-absolute C --max-modules A --max-average A --ignore '*py37-mac*' .
  - python -m pytest --color=yes --cov=./ -n auto merging_tests
# Push the results back to codecov
after_success:
  - codecov
