language: python
cache: pip
python:
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - pip install codecov python-Levenshtein
# commands to run, must exit 0 to pass
script:
  - flake8
  - yapf --parallel --verbose --recursive --style .style.yapf --exclude 'py38-mac' --diff .
  - find . -type f -name "*.py" ! -path "./py38-mac/*" ! -path "./merging_tests/*" | xargs pylint
  - vulture --exclude "*py37-mac*" .
  - xenon --max-absolute B --max-modules A --max-average A --ignore '*py38-mac*' .
  - python -m pytest --color=yes --cov=./merging_code -n auto merging_tests
# Push the results back to codecov
after_success:
  - codecov
