name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install codecov python-Levenshtein
    - name: run tests
      env:
        GEOCODE_API_KEY: ${{ secrets.GEOCODE_API_KEY }}
        QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
      run: |
        flake8 -v --exclude py3*-*
        yapf --parallel --verbose --recursive --style .style.yapf --exclude 'py3*-*' --diff .
        find . -type f -name "*.py" ! -path "./py3*-*/*" ! -path "./merging_tests/*" | xargs pylint
        vulture --exclude "*py3*-*" .
        xenon --max-absolute B --max-modules A --max-average A --ignore '*py3*-*' .
        python -m pytest --color=yes --cov=./merging_code -n auto merging_tests
        codecov
