name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install codecov python-Levenshtein
    - name: run tests 
      run: |
        flake8
        yapf --parallel --verbose --recursive --style .style.yapf --exclude 'py38-mac' --diff .
        find . -type f -name "*.py" ! -path "./py38-mac/*" ! -path "./merging_tests/*" | xargs pylint
        vulture --exclude "*py38-mac*" .
        xenon --max-absolute B --max-modules A --max-average A --ignore '*py38-mac*' .
        python -m pytest --color=yes --cov=./merging_code -n auto merging_tests
        codecov
